src/onekit/AppBundle/Entity/Doctor.php
<?php
namespace onekit\AppBundle\Entity;


use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use onekit\AppBundle\Validator\Constraints as AppAssert;
use JMS\Serializer\Annotation as Serial;

use onekit\AppBundle\Entity\Behavior\SoftDeletable;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass = "onekit\AppBundle\Repository\DoctorRepository")
 * @ORM\HasLifecycleCallbacks
 * @ORM\Table(name = "doctor", indexes = {
 *      @ORM\Index(name="expiry_index", columns={"expired_in"}),
 * })
 * @AppAssert\AtLeastOne({"address", "phone"})
 * @Gedmo\SoftDeleteable
 */
class Doctor
{
    use SoftDeletable;

    /**
     * @var integer
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Serial\Groups({"default", "doctor"})
     */
    protected $id;

    /**
     * @var \onekit\AppBundle\Entity\User
     *
     * @ORM\OneToOne(targetEntity="onekit\AppBundle\Entity\User", inversedBy="doctor")
     * @ORM\JoinColumn(name="account_id", referencedColumnName="id", nullable=false)
     * @Serial\MaxDepth(1)
     * @Serial\Groups({"doctor"})
     */
    protected $account;

    /**
     * @var string $title
     * @Assert\NotBlank()
     * @ORM\Column(name="title", type="string", length=255, nullable=false)
     * @Serial\Groups({"default", "doctor"})
     */
    protected $title;

    /**
     * @var string $address
     * @ORM\Column(name="address", type="text", nullable=true)
     */
    protected $address;

    /**
     * @var string $times
     * @ORM\Column(name="times", type="text", nullable=true)
     */
    protected $times;

    /**
     * @var string $email
     * @ORM\Column(name="email", type="string", length=255, nullable=true)
     * @Assert\Email()
     * @Serial\Groups({"doctor_contact"})
     */
    protected $email;

    /**
     * @var string $phone
     * @ORM\Column(name="phone", type="string", length=32, nullable=true)
     * @Serial\Groups({"doctor_contact"})
     */
    protected $phone;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Patient", mappedBy="doctor")
     */
    protected $patients;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Appointment", mappedBy="doctor")
     */
    protected $appointments;

    /**
     * @var $notifications \Doctrine\Common\Collections\ArrayCollection
     * @ORM\OneToMany(targetEntity="onekit\AppBundle\Entity\Notification", mappedBy="doctor")
     * @ORM\OrderBy({"created"="desc"})
     */
    protected $notifications;

    /**
     * @var $smsMessageTemplates \Doctrine\Common\Collections\ArrayCollection
     * @ORM\OneToMany(targetEntity="onekit\AppBundle\Entity\SMSMessageTemplate", mappedBy="doctor")
     */
    protected $smsMessageTemplates;

    /**
     * @var $schedules \Doctrine\Common\Collections\ArrayCollection
     * @ORM\OneToMany(targetEntity="onekit\AppBundle\Entity\Schedule", mappedBy="doctor")
     * @Serial\MaxDepth(2)
     */
    protected $schedules;

    /**
     * @var \DateTime $expiredIn
     * @ORM\Column(name="expired_in", type="datetime", nullable=true)
     */
    protected $expiredIn;

    /**
     * @return string
     */
    public function getLanguage()
    {
        return $this->getAccount()->getLanguage();
    }

    public function isExpired()
    {
        return !is_null($this->expiredIn) && $this->expiredIn < new \DateTime();
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->appointments = new ArrayCollection();
        $this->notifications = new ArrayCollection();
        $this->smsMessageTemplates = new ArrayCollection();
        $this->schedules = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set expiredIn
     *
     * @param \DateTime $expiredIn
     *
     * @return Doctor
     */
    public function setExpiredIn($expiredIn)
    {
        $this->expiredIn = $expiredIn;

        return $this;
    }

    /**
     * Get expiredIn
     *
     * @return \DateTime
     */
    public function getExpiredIn()
    {
        return $this->expiredIn;
    }

    /**
     * Set account
     *
     * @param User $account
     *
     * @return Doctor
     */
    public function setAccount(User $account)
    {
        $this->account = $account;

        return $this;
    }

    /**
     * Get account
     *
     * @return User
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * Add appointment
     *
     * @param Appointment $appointment
     *
     * @return Doctor
     */
    public function addAppointment(Appointment $appointment)
    {
        $this->appointments[] = $appointment;
    
        return $this;
    }

    /**
     * Remove appointment
     *
     * @param Appointment $appointment
     */
    public function removeAppointment(Appointment $appointment)
    {
        $this->appointments->removeElement($appointment);
    }

    /**
     * Get appointments
     *
     * @return ArrayCollection
     */
    public function getAppointments()
    {
        return $this->appointments;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Doctor
     */
    public function setTitle($title)
    {
        $this->title = $title;
    
        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set times
     *
     * @param string $times
     *
     * @return Doctor
     */
    public function setTimes($times)
    {
        $this->times = $times;

        return $this;
    }

    /**
     * Get times
     *
     * @return string
     */
    public function getTimes()
    {
        return $this->times;
    }

    /**
     * Set address
     *
     * @param string $address
     *
     * @return Doctor
     */
    public function setAddress($address)
    {
        $this->address = $address;

        return $this;
    }

    /**
     * Get address
     *
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Set email
     *
     * @param string $email
     *
     * @return Doctor
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set phone
     *
     * @param string $phone
     *
     * @return Doctor
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * Get phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Add patient
     *
     * @param \onekit\AppBundle\Entity\Patient $patient
     *
     * @return Doctor
     */
    public function addPatient(\onekit\AppBundle\Entity\Patient $patient)
    {
        $this->patients[] = $patient;

        return $this;
    }

    /**
     * Remove patient
     *
     * @param \onekit\AppBundle\Entity\Patient $patient
     */
    public function removePatient(\onekit\AppBundle\Entity\Patient $patient)
    {
        $this->patients->removeElement($patient);
    }

    /**
     * Get patients
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPatients()
    {
        return $this->patients;
    }

    /**
     * Add notification
     *
     * @param \onekit\AppBundle\Entity\Notification $notification
     *
     * @return Doctor
     */
    public function addNotification(\onekit\AppBundle\Entity\Notification $notification)
    {
        $this->notifications[] = $notification;

        return $this;
    }

    /**
     * Remove notification
     *
     * @param \onekit\AppBundle\Entity\Notification $notification
     */
    public function removeNotification(\onekit\AppBundle\Entity\Notification $notification)
    {
        $this->notifications->removeElement($notification);
    }

    /**
     * Get notifications
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getNotifications()
    {
        return $this->notifications;
    }

    /**
     * Add smsMessageTemplate
     *
     * @param \onekit\AppBundle\Entity\SMSMessageTemplate $smsMessageTemplate
     *
     * @return Doctor
     */
    public function addSmsMessageTemplate(\onekit\AppBundle\Entity\SMSMessageTemplate $smsMessageTemplate)
    {
        $this->smsMessageTemplates[] = $smsMessageTemplate;

        return $this;
    }

    /**
     * Remove smsMessageTemplates
     *
     * @param \onekit\AppBundle\Entity\SMSMessageTemplate $smsMessageTemplates
     */
    public function removeSMSMessageTemplate(\onekit\AppBundle\Entity\SMSMessageTemplate $smsMessageTemplates)
    {
        $this->smsMessageTemplates->removeElement($smsMessageTemplates);
    }

    /**
     * Get smsMessageTemplates
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSMSMessageTemplates()
    {
        return $this->smsMessageTemplates;
    }

    /**
     * Add Schedule
     *
     * @param \onekit\AppBundle\Entity\Schedule $schedule
     *
     * @return Doctor
     */
    public function addSchedule(\onekit\AppBundle\Entity\Schedule $schedule)
    {
        $this->schedules[] = $schedule;

        return $this;
    }

    /**
     * Remove Schedule
     *
     * @param \onekit\AppBundle\Entity\Schedule $schedule
     */
    public function removeSchedule(\onekit\AppBundle\Entity\Schedule $schedule)
    {
        $this->schedules->removeElement($schedule);
    }

    /**
     * Get schedules
     *

src/onekit/AppBundle/Controller/Admin/UserController.php
<?php

namespace onekit\AppBundle\Controller\Admin;

use Doctrine\ORM\EntityManager;
use Liip\ImagineBundle\Imagine\Cache;
use JMS\DiExtraBundle\Annotation as DI;

use onekit\AppBundle\Entity\SystemLog;
use onekit\AppBundle\Manager\UserManager;
use onekit\AppBundle\Repository\UserRepository;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use onekit\AppBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use onekit\AppBundle\Entity\Appointment;
use onekit\AppBundle\Entity\User;
use onekit\AppBundle\Entity\AdminUserSearch;
use onekit\AppBundle\Form\Type\UserFormType;
use onekit\AppBundle\Form\Type\AdminUserSearchType;
use onekit\AppBundle\Form\Type\AppointmentFormType;
use JMS\SecurityExtraBundle\Annotation\Secure;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

use Symfony\Component\HttpFoundation\Response;
use Doctrine\ORM\Query\Expr;

use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\File\File;

/**
 * Admin User controller.
 * @Security("has_role('ROLE_SUPER_ADMIN')")
 * @Route("/user")
 */
class UserController extends Controller
{

    /**
     * @var EntityManager
     */
    private $em;

    /**
     * @var UserRepository
     */
    private $repo;

    /**
     * @var UserManager
     */
    private $manager;
    private $imagine;

    /**
     * @DI\InjectParams({
     *     "em" = @DI\Inject("doctrine.orm.entity_manager"),
     *     "manager" = @DI\Inject("manager.user"),
     *     "imagine" = @DI\Inject("liip_imagine.controller"),
     * })
     *
     * @param EntityManager $em
     * @param $manager
     * @param $imagine
     */
    public function __construct(EntityManager $em, $manager, $imagine)
    {
        $this->em = $em;
        $this->repo = $em->getRepository('AppBundle:User');
        $this->manager = $manager;
        $this->imagine = $imagine;
    }


    /**
     * List of users
     * @Route("/list", name="admin_user", requirements={"type" = "html"})
     * @Template()
     *
     * @param Request $request
     * @return array
     */
    public function listAction(Request $request)
    {
        $sort = $request->get('sort') ? $request->get('sort') : 'u.id';
        $direction = $request->get('direction') ? $request->get('direction'):'desc';
        $userSearch = new AdminUserSearch();
        $options = ['csrf_protection' => false];
        $form = $this->createForm(new AdminUserSearchType(), $userSearch, $options);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $user =  $userSearch->user;
            if ($user instanceof User && $user->getId()) {
                return $this->redirect($this->generateUrl('admin_user_show', array('user_id' => $user->getId())));
            } else {
                $form->get('user')->addError(new FormError('Unknown user'));
            }
        }
        $limitPerPage = $request->get('limitPerPage') ? $request->get('limitPerPage') : 10;

        $qb = $this->repo->createQueryBuilder('u');
        $qb->groupBy('u.id');
        $qb->orderBy($sort,$direction);
        $qb->getQuery();

        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $qb,
            $this->get('request')->query->get('page', 1),
            $limitPerPage
        );
        return [
            'form'=>$form->createView(),
            'pagination' => $pagination,
            'user' => $this->getUser(),
            'limitPerPage' => $limitPerPage
        ];
    }

    /**
     * create User
     * @Route("/create", name="admin_user_create")
     * @Template()
     */
    public function createAction(Request $request)
    {
        $user = new User();
        $form = $this->createForm(new UserFormType(), $user);
        $form->handleRequest($request);
        if ($form->isValid()) {
            $this->get('fos_user.user_manager')->updateUser($user, true);
            return $this->redirect($this->generateUrl('admin_user_show', ['user_id' => $user->getId()]));
        }
        $result['form'] = $form->createView();
        $result['user'] = $user;
        return $result;
    }

    /**
     * Finds and displays a User entity.
     *
     * @Route("/{user_id}/show", name="admin_user_show")
     * @Method("GET")
     * @Template()
     *
     * @param $user_id
     * @return array
     */
    public function showAction($user_id)
    {
        $entity = $this->repo->find($user_id);

        if (!$entity) {
            throw $this->createNotFoundException('not found');
        }

        return array(
            'entity' => $entity,
        );
    }

    /**
     * Edit User
     * @Route("/{user_id}/edit", name="admin_user_edit")
     * @Template()
     */
    public function editAction(Request $request, $user_id = null)
    {
        $user = $this->repo->find($user_id);
        $form = $this->createForm(new UserFormType(), $user);
        $form->handleRequest($request);
        if ($form->isValid()) {
            $this->get('fos_user.user_manager')->updateUser($user, true);
            return $this->redirect($this->generateUrl('admin_user_show', ['user_id' => $user->getId()]));
        }
        $result['form'] = $form->createView();
        $result['user'] = $user;
        return $result;
    }


    /**
     * Delete user
     * @Route("/{user_id}/delete", name="admin_user_delete")
     * @Template()
     */
    public function deleteAction($user_id)
    {
        $user = $this->repo->find($user_id);
        if ($user) {
                $this->manager->disable($user);
        }
        return $this->redirect($this->generateUrl('admin_user'));
    }

    /**
     * @Route("/autocomplete", name="admin_user_autocomplete")
     */
    public function autocompleteAction(Request $request)
    {
        /** @var User[] $results */
        $results = $this->manager->adminAutocomplete(
            $request->request->get('query'),
            intval($request->request->get('page', 1)),
            intval($request->request->get('limit', 25))
        );
        foreach ($results as &$user) {
            $user = array(
                'id' => $user->getId(),
                'value' => sprintf('"%s" &lt;%s&gt;', $user->getUsername(), $user->getEmail()),
            );
        }

        $response = new Response(json_encode($results));
        $response->headers->set('Content-Type', 'application/json');

        return $response;
    }

}

src/onekit/AppBundle/Controller/UserController.php
<?php

namespace onekit\AppBundle\Controller;

use Liip\ImagineBundle\Imagine\Cache;
use JMS\DiExtraBundle\Annotation as DI;

use Symfony\Component\HttpFoundation\Request;
use onekit\AppBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use JMS\SecurityExtraBundle\Annotation\Secure;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

use Symfony\Component\HttpFoundation\Response;
use Doctrine\ORM\Query\Expr;


/**
 * @Security("has_role('ROLE_USER')")
 * @Route("/user")
 */
class UserController extends Controller
{


    /**
     * @Route("/", name="user")
     */
    public function indexAction()
    {
        return $this->redirect($this->generateUrl('user_appointment'));
    }

}

src/onekit/AppBundle/Resources/views/Admin/User/create.html.twig
{% extends 'AppBundle:Layout:admin.html.twig' %}
{% form_theme form 'AppBundle:Form:form_horizontal.html.twig' %}
{% block title %}{{ 'breadcrumbs.admin_user_create'|trans }}{% endblock %}
{% block body %}
<div class="bb">
    <h1>{{ 'breadcrumbs.admin_user_create'|trans }}</h1>
    {{ form_start(form,{'attr': {'class': 'form', 'id': 'user_upload' }})}}

    <div class="form-group">
        {{ form_label(form.roles) }}
        {{ form_widget(form.roles) }}
        {{ form_errors(form.roles) }}
    </div>

    <div class="form-group">
        {{ form_label(form.language) }}
        {{ form_widget(form.language) }}
        {{ form_errors(form.language) }}
    </div>
    <div class="form-group">
        {{ form_label(form.gender) }}
        {{ form_widget(form.gender) }}
        {{ form_errors(form.gender) }}
    </div>
    <div class="form-group">
        {{ form_label(form.username) }}
        {{ form_widget(form.username) }}
        {{ form_errors(form.username) }}
    </div>
    <div class="form-group">
        {{ form_label(form.email) }}
        {{ form_widget(form.email) }}
        {{ form_errors(form.email) }}
    </div>
    <div class="form-group">
        {{ form_label(form.firstname) }}
        {{ form_widget(form.firstname) }}
        {{ form_errors(form.firstname) }}
    </div>
    <div class="form-group">
        {{ form_label(form.lastname) }}
        {{ form_widget(form.lastname) }}
        {{ form_errors(form.lastname) }}
    </div>
    <div class="form-group">
        {{ form_label(form.phone) }}
        {{ form_widget(form.phone) }}
        {{ form_errors(form.phone) }}
    </div>
    <div class="form-group">
        {{ form_label(form.plainPassword) }}
        {{ form_widget(form.plainPassword) }}
        {{ form_errors(form.plainPassword) }}
    </div>
    <div class="form-group">
        {{ form_widget(form.enabled) }}
        {{ form_label(form.enabled) }}
    </div>
    {{ form_end(form) }}
</div>
 {% endblock %}

src/onekit/AppBundle/Resources/views/Admin/User/edit.html.twig
{% extends 'AppBundle:Layout:admin.html.twig' %}
{% form_theme form 'AppBundle:Form:form_horizontal.html.twig' %}
{% block title %}{{ 'breadcrumbs.admin_user_edit'|trans }}{% endblock %}
{% block body %}
<div class="bb">
    <h1>{{ 'breadcrumbs.admin_user_edit'|trans }}</h1>
    {{ form_start(form,{'method': 'POST', 'action': path('admin_user_edit',{'user_id': user.id}), 'attr': {'class': 'form', 'id': 'user_upload' }})}}

    <div class="form-group">
        {{ form_label(form.language) }}
        {{ form_widget(form.language) }}
        {{ form_errors(form.language) }}
    </div>
    <div class="form-group">
        {{ form_label(form.username) }}
        {{ form_widget(form.username) }}
        {{ form_errors(form.username) }}
    </div>
    <div class="form-group">
        {{ form_label(form.email) }}
        {{ form_widget(form.email) }}
        {{ form_errors(form.email) }}
    </div>
    <div class="form-group">
        {{ form_label(form.plainPassword) }}
        {{ form_widget(form.plainPassword) }}
        {{ form_errors(form.plainPassword) }}
    </div>

    <div class="form-group">
            {{ form_widget(form.enabled) }}
            {{ form_label(form.enabled) }}
    </div>
    {{ form(form) }}
    {{ form_end(form) }}
</div>
{% endblock %}

src/onekit/AppBundle/Resources/views/Admin/User/list.html.twig
{% extends 'AppBundle:Layout:admin.html.twig' %}
{% form_theme form 'AppBundle:Form:form_horizontal.html.twig' %}
{% block title %}{{ 'breadcrumbs.admin_user_list'|trans }}{% endblock title %}
{% block description %}{{ 'breadcrumbs.admin_user_list'|trans }}{% endblock %}
{% block body %}
    <div class="app-section__filter">
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 bb">
            <div class="btn-group">
                <a class="btn btn-xs btn-primary" href="{{ path('admin_user_create') }}">{{ 'breadcrumbs.admin_user_create'|trans }}</a>
            </div>
        </div>
    </div>

    <div class="app-section__filter">
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            {{ form_start(form,{'attr': {'class': 'form-inline', 'id': 'search' }} ) }}
            <div class="form-group">
                {{ form_widget(form.user) }}
                {{ form_errors(form.user) }}
            </div>
            <div class="form-group">
                {{ form_widget(form.go) }}
            </div>
            {{ form_end(form) }}
        </div>

        {% if pagination|length %}
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 text-right">
                {{ knp_pagination_render(pagination) }}
            </div>
        {% endif %}

        {% if pagination|length == 0 %}
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <h2 class="text-danger">{{ 'Empty result'|trans }}.</h2>
            </div>
        {% endif %}
    </div>

    {% if pagination|length %}
        <div>
            <table class="table table-condensed">
                <thead>
                <tr>
                    <th class="hidden-xs text-center">{{ knp_pagination_sortable(pagination, 'ID', 'u.id') }}</th>
                    <th class="">{{ knp_pagination_sortable(pagination, 'Login'|trans, 'u.username') }}</th>
                    <th class="hidden-xs">{{ knp_pagination_sortable(pagination, 'Email'|trans, 'u.email') }}</th>
                    <th class="">{{ 'Doctor'|trans }}</th>
                    <th class="hidden-xs text-center">{{ knp_pagination_sortable(pagination, 'Created'|trans, 'u.created') }}</th>
                    <th class="text-right">{{ 'Actions'|trans }}</th>
                </tr>
                </thead>
                <tbody>
                {% for entity in pagination %}

                    <tr class="{% if entity.isDeleted %}bg-warning{% else %}bg-success{% endif %}">

                        <td class="hidden-xs text-center">{{ entity.id }}</td>
                        <td class="">
                            <a href="{{ path('admin_user_show', { 'user_id': entity.id }) }}">
                                {{ entity.username }}
                            </a>
                        </td>
                        <td class="hidden-xs">{{ entity.email }}</td>
                        <td class="">
                            {% if entity.isDoctor %}
                                <a href="{{ path('admin_doctor_show', { 'id': entity.getDoctor.getId }) }}">
                                    {{ entity.getDoctor.getTitle }}
                                </a>
                            {% endif %}
                        </td>
                        <td class="hidden-xs text-center">
                            {% if entity.created %}
                                {% if (app.request.locale=='en') %}
                                    {{ entity.created|date('h:i A / M d, Y') }}
                                {% else %}
                                    {{ entity.created|date('H:i / M d, Y') }}
                                {% endif %}
                            {% endif %}
                        </td>
                        <td>
                            <div class="btn-group pull-right">
                                <a
                                    class = "btn btn-xs btn-default"
                                    href = "{{ path('admin_user_edit', { 'user_id': entity.id }) }}"
                                >
                                    {{ 'breadcrumbs.admin_user_edit'|trans }}
                                </a>
                                {% if entity.isDeleted %}
                                {% else %}
                                    <a
                                        class = "btn btn-xs btn-danger confirm"
                                        href = "{{ path('admin_user_delete', { 'user_id': entity.id }) }}"
                                        title = "{{ 'delete user'|trans }} {{ entity.username }}"
                                    >
                                        {{ 'breadcrumbs.admin_user_delete'|trans }}
                                    </a>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 bb text-right">
            {{ knp_pagination_render(pagination) }}
        </div>

    {% endif %}

{% endblock %}
{% block javascripts_after %}
    {{ parent() }}
    <script type="text/javascript">
        function unescapeHtml(text, data)
        {
            this.$element.val($('<div />').html(text).text());
        }

        $(document).on("click", ".confirm", function(e) {
            var link = $(this).attr("href");
            var title = $(this).attr("title");
            e.preventDefault();
            bootbox.setLocale('{{ app.request.locale }}');
            bootbox.confirm(
                    {
                        size: 'small',
                        message: "{{ 'Are you sure you want to'|trans }} "+ title +" ?",
                        callback: function(result) {
                            if (result) {
                                document.location.href = link;
                            }
                        }
                    }
            );
        });
    </script>
{% endblock %}

src/onekit/AppBundle/Resources/views/Admin/User/show.html.twig
{% extends 'AppBundle:Layout:admin.html.twig' %}

{% block body %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 bb">
        <h2>
            {{ entity.username }}
        </h2>
        <p>ID: {{ entity.id }}</p>
        <p>{{ 'Username'|trans }}: {{ entity.username }}</p>
        <p>{{ 'Created'|trans }}:

            {% if (app.request.locale=='en') %}
                {{ entity.created|date('h:i A / M d, Y') }}
            {% else %}
                {{ entity.created|date('H:i / M d, Y') }}
            {% endif %}

        </p>
        <div class="bb">
            <div class="btn-group">
                <a class="btn btn-default" href="{{ path('admin_user_edit', {'user_id':entity.id}) }}">
                    {{ 'breadcrumbs.admin_user_edit'|trans }}
                </a>
                <a href="{{ path('admin_doctor_create', {'user_id': entity.id}) }}" class="btn btn-primary">
                    {{ 'breadcrumbs.admin_doctor_create'|trans }}
                </a>
            </div>
        </div>
    </div>

{% endblock %}